import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/favicon/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon/favicon-16x16.png"
          />
          <link rel="manifest" href="/favicon/site.webmanifest" />
		  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3379264460534244"
		       crossorigin="anonymous"></script>
        </Head>
        <body>
          <Main />
          <NextScript />
	  <div class="content-container">
	    <h1>About YoutTube Thumbnail Downloader - Easily Download YouTube Thumbnails</h1>
	    <p>
	      Discover the convenience of TubeThumbnail, YouTube thumbnail downloader. Download YouTube thumbnails quickly and effortlessly with this online tool. No app installation required – it's completely free for everyone.
	    </p>

	    <h2>Understanding YouTube Thumbnails</h2>
	    <p>
	      YouTube thumbnails offer a preview of videos, serving as cover images. They come in two types: those automatically generated by YouTube and custom thumbnails uploaded by creators. Unfortunately, these thumbnail URLs are hidden on YouTube, making them impossible to find or save.
	    </p>

	    <h2>Number of Thumbnails per Video</h2>
	    <p>
	      Each YouTube video can have up to nine thumbnails, although not all videos have that many. Among these, seven are guaranteed:
	    </p>
	    <ul>
	      <li>Player Background (480x360)</li>
	      <li>Start (120x90)</li>
	      <li>Middle (120x90)</li>
	      <li>End (120x90)</li>
	      <li>High-Quality (480x360)</li>
	      <li>Medium Quality (320x180)</li>
	      <li>Normal Quality (120x90)</li>
	    </ul>
	    <p>Additionally, high-definition videos feature two more thumbnail sizes:</p>
	    <ul>
	      <li>Standard Definition (640x480)</li>
	      <li>Maximum Resolution (1920x1080)</li>
	    </ul>
	    <p>However, the most commonly used sizes are High-Quality, Medium Quality, and full size. Therefore, the TubeThumbnail Downloader offers downloads exclusively in these three sizes. For other sizes, instructions are available.</p>

	    <h2>Why Download Thumbnails?</h2>
	    <p>
	      YouTube video thumbnails hold significant metadata value, as creators thoughtfully design these video covers. The captivating and creative video covers on YouTube often entice users to download and save them. Reasons include:
	    </p>
	    <ul>
	      <li>Setting thumbnails as wallpapers</li>
	      <li>Sharing thumbnails on blogs or social media</li>
	      <li>Gaining inspiration for video covers</li>
	    </ul>

	    <h2>Why Choose TubeThumbnail Downloader?</h2>
	    <p>
	      Although various tools can fetch thumbnails, the process is far from simple. TubeThumbnail Downloader offers an uncomplicated solution to the challenge of saving video covers.
	    </p>

	    <h2>Using TubeThumbnail Downloader</h2>
	    <p>
	      Utilizing the TubeThumbnail Downloader is straightforward:
	    </p>
	    <ol>
	      <li>Copy and paste the video URL into the search box.</li>
	      <li>The downloader automatically extracts three thumbnail sizes.</li>
	      <li>Choose and download your preferred thumbnail. HD thumbnails are recommended.</li>
	    </ol>

	    <h2>Obtaining All Thumbnail Sizes</h2>
	    <p>
	      While a video can feature up to nine thumbnails of varying sizes, obtaining them all requires familiarity with video IDs. The video ID is a unique identifier found in the video URL. It's typically the string of characters following "v=" or after the "youtu.be/" domain. Use these thumbnail links, replacing "VIDEO-ID" with your video's ID, to access all sizes:
	    </p>
	    <ul>
	      <li>480x360	: https://i1.ytimg.com/vi/VIDEO-ID/0.jpg</li>
	      <li>120x90	: https://i1.ytimg.com/vi/VIDEO-ID/1.jpg</li>
	      <li>120x90	: https://i1.ytimg.com/vi/VIDEO-ID/2.jpg</li>
	      <li>120x90	: https://i1.ytimg.com/vi/VIDEO-ID/3.jpg</li>
	      <li>480x360	: https://i1.ytimg.com/vi/VIDEO-ID/hqdefault.jpg</li>
	      <li>320x180	: https://i1.ytimg.com/vi/VIDEO-ID/mqdefault.jpg</li>
	      <li>120x90	: https://i1.ytimg.com/vi/VIDEO-ID/default.jpg</li>
	      <li>640x480	: https://i1.ytimg.com/vi/VIDEO-ID/sddefault.jpg</li>
	      <li>1920x1080	: https://i1.ytimg.com/vi/VIDEO-ID/maxresdefault.jpg</li>
	    </ul>

	    <h2>Using Downloaded Thumbnails</h2>
	    <p>
	      Remember, the copyright of thumbnails belongs to their creators or designers. Using these without permission can result in legal actions. However, they can serve as design inspiration for your creations.
	    </p>

	    <p>
	      Enhance your YouTube thumbnail experience with TubeThumbnail Downloader. Easily access and download high-quality thumbnails for your videos. Try it now – it's free, simple, and effective.
	    </p>
	  </div>
		  
        </body>
      </Html>
    );
  }
}

export default MyDocument;
